Jack/update documentation
Unstructured-IO/unstructured pull request #1190
Opened 2023-08-23 22:50 UTC by jackretterer

Updated:

- Added back support document types for partitioning
- Added more tabs for python code in the API page
- Added a RAG section in Key Concepts
- Added a Common Use case section in overview

2023-08-25 18:24 UTC, cragwolfe commented
i think we're due for a release, especially with the element ordering change with fast + hi_res strategies for images and PDF's.
may as well make this a release? (remove -devX from the top line of the changelog, edit unstructured/__version__.py to be consistent)

2023-08-26 00:00 UTC, cragwolfe commented on docs/source/introduction/overview.rst
> +- **Retrieval Augmented Generation (RAG)**
perhaps this should be top of the list?

2023-08-26 00:06 UTC, cragwolfe commented
Looks like a markdown format issue for one row:

![image](https://github.com/Unstructured-IO/unstructured/assets/28578599/211f15e2-6ac2-4b40-a2f9-9b97b317688c)

2023-08-29 01:31 UTC, ron-unstructured commented on docs/source/bricks/partition.rst
> +| PDFs (`.pdf`)                                | `partition_pdf`     | `"auto"`, `"fast"`, `"hi_res"`, `"ocr_only"` | Yes | Encoding; Include Page Breaks; Infer Table Structure; Max Partition; OCR La
the table alignment is off

2023-08-29 01:33 UTC, ron-unstructured requested changes
Hi @jackretterer, please resolve the comments before we merge. Thanks.

2023-09-04 04:14 UTC, ron-unstructured approved these changes

2023-09-04 16:15 UTC, merged