fix: split on para breaks in `partition_html`.
Unstructured-IO/unstructured pull request #1275
Opened 2023-09-01 17:19 UTC by MthwRobinson

### Summary

Closes #1230. Updates `partition_html` to split sections separated by paragraph breaks into distinct elements.

### Testing

The following splits into two elements on the feature branch and is a single element on `main`.

```python
from unstructured.partition.html import partition_html 

html_text = "<html><p>I'm a parrot.\nParrots like to squawk<p></html>" 
elements = partition_html(text=html_text)
```

2023-09-02 01:25 UTC, qued requested changes
This seems to break up the text by the placement of the newlines in the raw HTML. Looking at the raw and rendered HTML, I think it would be better to break by the placement of the `<br>` (and other similar) tags.

2023-09-02 01:25 UTC, qued commented on test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/ideas-page.json
> +    "text": "questions based on them, then asked it where good ideas come from. The"
This fragmented text seems worse to me. Also the emphasized text contents seems to be derived from the text before it was split.

2023-09-02 03:40 UTC, Klaijan commented on test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
These results look suspicious to me. It seems like it breaks when applying `split_by_paragraph` on top of the extracted html text which was not in the intended paragraph format. I also agree that splitting with `<br>` could result in a prettier output :)

2023-09-02 03:41 UTC, Klaijan commented on test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
> +        "(Someone fed my essays into GPT to make something that could answer\nquestions based on them, then asked it where good ideas come from.  The\nanswer was ok, but not what I would have said. T
These results look suspicious to me. It seems like it breaks when applying `split_by_paragraph` on top of the extracted html text which was not in the intended paragraph format. I also agree that splitting with `<br>` could result in a prettier output :)

2023-09-02 03:41 UTC, Klaijan commented on test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
> +    "text": "questions based on them, then asked it where good ideas come from. The"
These results look suspicious to me. It seems like it breaks when applying `split_by_paragraph` on top of the extracted html text which was not in the intended paragraph format. I also agree that splitting with `<br>` could result in a prettier output :)

2023-09-06 04:00 UTC, qued commented
I'm not sure if this is ready for re-review yet, but I tried it out on `ideas-page.html` just now, and elements 1-3 looked like what we expect, but element 0 was all the text repeated a few times.

2023-09-06 19:36 UTC, MthwRobinson commented
@qued - Closing in favor of #1314. Found a simpler way to do this.

2023-09-06 19:36 UTC, closed without merging