chore: bump `unstructured-inference` to `0.6.1`
Unstructured-IO/unstructured pull request #1490
Opened 2023-09-21 17:04 UTC by badGarnet

Bump `unstructured-inference`:
- now uses `yolox_quantized` as default element detection model for pdf/image partition in `hi_res`
- dedupe nested elements
- allow setting inference parameters via environment variables

2023-09-25 22:14 UTC, badGarnet commented on test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
> +    "element_id": "c1f4b5ba045830c1866db8f8aa0b54ac",
due to using yolox -> better element classification

2023-09-25 22:16 UTC, badGarnet commented on test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
> +  },
seems to be part duplicated text, cc @benjats07 for double check this behavior

2023-09-25 22:17 UTC, badGarnet commented on test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
> +    "element_id": "836e6ef5cecc9a73356c0d5bee181829",
this is just swapped in location with the element below

2023-09-28 04:11 UTC, cragwolfe requested changes
This bump is 3 minor versions behind the latest `unstructured-inference==0.6.6` (as of writing) so I think the priority is getting to parity. To do that, I'd propose two PR's:

* update this PR to bump to `unstructured-inference==0.6.6` changing the default model name to `detectron2_onnx`. this will isolate diff's in fixtures not related to updating the model
* once merged, create another PR to update the default model. then, carefully examine the ingest test diffs. IRS-form-1987.png is one I'd focus on first.

CC @christinestraub as https://github.com/Unstructured-IO/unstructured/issues/1233 may be necessary before the last bullet to keep the existing good natural-reading-order outputs that currently exist in fixture output.

2023-09-28 21:10 UTC, christinestraub commented
@cragwolfe Created PR [#1560](https://github.com/Unstructured-IO/unstructured/pull/1560) for #1233.

2023-09-29 22:01 UTC, badGarnet commented
breaking this task with other PRs.

2023-09-29 22:01 UTC, closed without merging