fixed the issue 149
Unstructured-IO/unstructured pull request #182
Opened 2023-01-30 10:00 UTC by sparkbrains

Added regex to eliminate script tags as well as strings in between.

2023-02-02 15:01 UTC, MthwRobinson commented on unstructured/documents/xml.py
> +        content = re.sub(r"<script[\s\S]*?(.*?)</script>", "", content, flags=re.IGNORECASE)
Have you looked at this regex warning from the automated scans?

2023-02-02 15:03 UTC, MthwRobinson requested changes
Please update the PR title so its formatted like `fix: <description-of-fix>`. Please also reference the issue in the PR description and add a testing section to the PR description with test instructions. Thanks for the contribution!

2023-02-02 19:59 UTC, sparkbrains commented on unstructured/documents/xml.py
> +        content = re.sub(r"<script[\s\S]*?(.*?)</script>", "", content, flags=re.IGNORECASE)
Yes I have seen the warning. But the regex does match those tags

2023-02-03 17:28 UTC, cragwolfe commented
The CodeQL issue looks legit, see https://codeql.github.com/codeql-query-help/python/py-bad-tag-filter/#example , "Browsers will not only accept </script> as script end tags, but also tags such as </script foo="bar">" so we may as well make the regex handle that that and add a test case.

2023-02-03 17:34 UTC, MthwRobinson commented
I'd also prefer just skipping script tags (and their child tags) when we iterate over the HTML tags versus substituting out the `<script>` content with the regex.

2023-02-03 21:32 UTC, sparkbrains commented
okay I will make edits accordingly.

2023-02-06 23:12 UTC, sparkbrains commented
I have fixed the CodeQL Issue. Can you check now?

2023-02-07 14:12 UTC, MthwRobinson requested changes
Instead of replacing the script tags with a regex, I'd prefer to skip the `script` tag as we iterate over the tags in the documents. You'd be able to accomplish that by skipping `script` tags and adding its descendants to `descendanttag_elems` here:

https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/documents/html.py#L101

2023-02-15 22:26 UTC, MthwRobinson commented
Closing this PR. Per [this comment](https://github.com/Unstructured-IO/unstructured/issues/149#issuecomment-1432128327), the offending JS in the example document is coming in from a `td` and it appears we're already skipping `script` tags. Updated #149 accordingly

2023-02-15 22:26 UTC, closed without merging