fix: handle delimiter bug in partition_csv
Unstructured-IO/unstructured pull request #2224
Opened 2023-12-06 19:58 UTC by awalker4

Closes #2218. When a csv has commas in its content, and the delimiter is something else, Pandas may throw an error. We can sniff the csv and get the correct delimiter to pass to Pandas. To verify, try partitioning the file in the linked bug.

2023-12-06 20:32 UTC, christinestraub requested changes
The `get_delimiter()` function gets this error. - `_csv.Error: Could not determine delimiter` on the CSV file in the linked bug.

2023-12-10 19:03 UTC, awalker4 commented
Ah, looks like I wasn't reading enough of the file in the csv sniffer.

2023-12-12 17:35 UTC, Coniferish approved these changes
LGTM once checks pass

2023-12-13 20:50 UTC, awalker4 commented on unstructured/partition/csv.py
> +def get_delimiter(file_path=None, file=None):
Hmm, the file was working for me after I bumped to 8192 bytes. Is it still failing for you locally?

2023-12-13 21:11 UTC, Coniferish commented on unstructured/partition/csv.py
> +def get_delimiter(file_path=None, file=None):
No, that comment was before you bumped the bytes. It worked for me last I tested (after you bumped it up)

2023-12-13 22:04 UTC, christinestraub approved these changes
It works after bumping the bytes. LGTM!

2023-12-13 23:19 UTC, awalker4 commented
One of the ingest test files is picking up ` ` as the delimiter. The bug was originally with `;` files, so I'm going to restrict the sniffer to check for `[",", ";"]`. We can expand this if other issues come in.

2023-12-14 00:37 UTC, merged