Refactor/rename pdf image extracting kwarg
Unstructured-IO/unstructured pull request #2303
Opened 2023-12-20 18:50 UTC by christinestraub

Currently, we're using different kwarg names in partition() and partition_pdf(), which has implications for the API since it goes through partition().
`auto.partition()` uses `pdf_extract_images` and `pdf_image_output_dir_path` , but
`pdf.partition_pdf()` uses `extract_images_in_pdf` and `image_output_dir_path`

It makes sense to drop the `pdf_` once we are in the `partition_pdf` pipeline.
so...
`auto.partition()`: `pdf_extract_images`  and `pdf_image_output_dir_path`
pdf.partition_pdf() : `extract_images` and `image_output_dir_path`

2023-12-20 18:55 UTC, Coniferish commented
Looks good. Only question/concern is if `extract_images_in_pdf` needs to just be deprecated instead of replaced. I'd assume if it was recently added it'd be safe to do so, but will leave that to @qued 's discretion.

2023-12-20 19:01 UTC, christinestraub commented
> Looks good. Only question/concern is if `extract_images_in_pdf` needs to just be deprecated instead of replaced. I'd assume if it was recently added it'd be safe to do so, but will leave that to @qued 's discretion.

CC: @cragwolfe

2023-12-20 19:11 UTC, cragwolfe commented on unstructured/partition/pdf.py
> -    extract_images_in_pdf
let's keep the old kwarg around as a deprecated argument for awhile to avoid breaking changes.

2023-12-28 15:57 UTC, Coniferish commented
[re: comment here](https://github.com/Unstructured-IO/unstructured/pull/2310) I wish I had thought of this earlier, but with so many interdependent parameters, I wonder if it would made more sense to have `extract_to_payload` be a Tuple(str, list) instead of a list. Then the first index could be used to determine `extract_to_payload` or `image_output_dir_path` since those two parameters seem to be mutually exclusive.

2023-12-28 20:18 UTC, christinestraub commented
> [re: comment here](https://github.com/Unstructured-IO/unstructured/pull/2310) I wish I had thought of this earlier, but with so many interdependent parameters, I wonder if it would made more sense to have `extract_to_payload` be a Tuple(str, list) instead of a list. Then the first index could be used to determine `extract_to_payload` or `image_output_dir_path` since those two parameters seem to be mutually exclusive.

@Coniferish Are you referring to something like this?
CC: @cragwolfe
```
element_extraction=("payload", ["Image", "Table"])
or 
element_extraction = ("output_dir", ["Image", "Table"])
```

2023-12-28 20:43 UTC, Coniferish commented
> @Coniferish Are you referring to something like this?

Yah, that's what I was thinking @christinestraub

2024-01-03 20:16 UTC, Coniferish approved these changes
LGTM! I like these names a lot more!

2024-01-03 20:29 UTC, Coniferish requested changes
Just noticing that this is removing the old params, but @cragwolfe mentioned keeping/deprecating them instead

2024-01-03 20:45 UTC, christinestraub commented
> Just noticing that this is removing the old params, but @cragwolfe mentioned keeping/deprecating them instead

For the `extract_images_in_pdf` param, I kept it in both `auto.partition()` and `partition.pdf()`
For the `image_output_dir_path` param, I renamed it to `extract_image_block_output_dir` since this param is optional (can be omitted), so this update will not bring the breaking change. CC: @cragwolfe

2024-01-03 22:00 UTC, Coniferish approved these changes

2024-01-04 18:37 UTC, merged