included the previous PR changes and verified black
Unstructured-IO/unstructured pull request #268
Opened 2023-02-23 15:41 UTC by firedragonironfist

This change resolves #228 I added the changes from the previous pull request and also rectified the black usage error. Please let me know if you have any further feedback or concerns.

Signed-off-by: Yousuf <yousufmohd223@gmail.com>

2023-02-23 16:55 UTC, MthwRobinson requested changes
Added inline comments. `filetype.py` is looking pretty good! This PR shouldn't change
`examples/ingest/s3-small-batch/main.py`, you can revert that with `git checkout main -- examples/ingest/s3-small-batch/main.py`. Looks like there are some merge conflicts to resolve as well.

2023-02-23 16:55 UTC, MthwRobinson commented on unstructured/file_utils/filetype.py
> +            if not LIBMAGIC_AVAILABLE:
Move this check above `mime_type = magic.from_file(filename, mime=True)`, otherwise you'll get an error if `libmagic` isn't installed

2023-02-23 18:10 UTC, firedragonironfist commented
Ok i will resolve them

2023-02-24 07:53 UTC, firedragonironfist commented
Please let me know if you have any further feedback or concerns.

2023-02-24 15:07 UTC, MthwRobinson approved these changes

2023-02-24 15:23 UTC, merged