feat: Create spacy notebook example
Unstructured-IO/unstructured pull request #593
Opened 2023-05-16 14:54 UTC by mallorih

This PR create an example notebook for using Unstructured with Spacy.

**Not sure why there are 8 files on this PR. Github automatically added them. I do not have these changes locally**

2023-05-16 15:09 UTC, MthwRobinson requested changes
Notebook code looks good, just made one suggestion to help target the data extraction use case. Couple other notes:

- On those other files that got into the PR, I'd give `git checkout main -- requirements/ ** git checkout main -- docs/requirements.txt` a try, that should revert those files.
- Could you add a brief `README` in the `examples/spacy` folder and also a `requirements.txt` with `spacy` and `unstructured`?
- I'd add a little more explanation for what's going on in the spacy section of the notebook.

2023-05-16 19:15 UTC, MthwRobinson approved these changes
Notebook updates look good! LGTM once you add the `requirements.txt` for the example notebook.

2023-05-16 19:17 UTC, mallorih commented
> Notebook updates look good! LGTM once you add the `requirements.txt` for the example notebook.

Forgot to add them to the commit 🤦‍♀️.

2023-05-17 19:48 UTC, MthwRobinson commented on test_unstructured_ingest/test-ingest-against-api.sh
>  if [ "$(find 'api-ingest-output' -type f -printf '.' | wc -c)" != 4 ]; then
I think you need `5` here, and then change the `echo` to `5` as well

2023-05-17 20:42 UTC, merged