Python script to collect environment for debugging issues
Unstructured-IO/unstructured pull request #989
Opened 2023-07-28 14:08 UTC by ron-unstructured

The script collect the following information:
- OS version
- Python version
- Unstructured and Unstructured-Inference (if installed) versions
- Tesseract versions and tesseract lang packages installed
- Detectron2 version, torch version
- PaddleOCR versions
- other OS packages: libmagic, libreoffice

2023-07-28 14:28 UTC, ron-unstructured commented
resolved issue #544

2023-07-28 14:49 UTC, MthwRobinson commented
@ron-unstructured - Could you run `make tidy` to resolve the linting errors?

2023-07-28 17:34 UTC, MthwRobinson requested changes
Looks good overall! Just a few minor comments

2023-07-28 17:34 UTC, MthwRobinson commented on scripts/collect_env.py
> +        subprocess.run([command], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
Can we look for the command in `PATH` instead of running the command? This seems like it would execute the command.

2023-07-28 17:34 UTC, MthwRobinson commented on scripts/collect_env.py
> +def is_python_package_installed(package_name):
For this one you could use `dependency_exists` from `unstructured.utils`

https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/utils.py#L50

2023-07-28 17:34 UTC, MthwRobinson commented on scripts/collect_env.py
> +        subprocess.run([command], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
Alternatively, you could make this `brew_command_exists` and have it do `brew help` since I only see it checking for `brew` in the script.

2023-08-02 14:00 UTC, MthwRobinson commented
Could you add documentation (probably in the GitHub issue template) on how to use this? This looks good otherwise.

2023-08-02 22:54 UTC, merged